### ISSUE TITLE
More Devices

### ISSUE THREAD

**Issue by burylo** [berezhinskiy/ecoflow_exporter#62]
Is there any way to add 2 charging stations and shoot graphics from both at the same time?

**Comment by setevoy2** [comment]
At this moment, only by running 2 exporters.

In the `compose.yml` - add a new container, update the `container_name`, `ports`, `EXPORTER_PORT`, and a new `DEVICE_SN`:

```
  ecoflow_exporter:
    image: ghcr.io/berezhinskiy/ecoflow_exporter
    container_name: ecoflow_exporter
    ports:
      - 9091:9091
    restart: unless-stopped
    environment:
      DEVICE_SN: <SN>DAEBZ5KF1183072
      ECOFLOW_USERNAME: user@mail.com
      ECOFLOW_PASSWORD: "password"
      EXPORTER_PORT: 9091

  ecoflow_exporter_2:
    image: ghcr.io/berezhinskiy/ecoflow_exporter
    container_name: ecoflow_exporter_2
    ports:
      - 9092:9092
    restart: unless-stopped
    environment:
      DEVICE_SN: DCEBZ8ZF2280341
      ECOFLOW_USERNAME: user@mail.com
      ECOFLOW_PASSWORD: "password"
      EXPORTER_PORT: 9092
```

And in the `/promethues/prometheus.yml` - add a new container's name and a corresponding port to the `targets`, so Prometheus will know where to pull new metrics:

```
  - job_name: ecoflow
    static_configs:
      - targets:
          - ecoflow_exporter:9091
          - ecoflow_exporter_2:9092
```

Then, in Grafana, you'll have two devices:

![image](https://github.com/user-attachments/assets/d6e24dc6-4ee2-4e61-8c86-257d7e6c8848)
